### ISSUE TITLE
Applying bigger role circles to permissions viewer plugin too

### ISSUE THREAD

**Issue by casKd-dev** [CapnKitten/BetterDiscord#8]
## The theme breaks the Permissions Viewer plugin
_Had this fix for a while and decided to make a request to add it to the theme_

### Before fix
![Before](https://s5.postimg.cc/h6ix9f507/screenshot_252.png)

### After fix
![After](https://s5.postimg.cc/jb3aaiecn/screenshot_253.png)

Code for fix:
```css
.member-perms .member-perm .perm-circle {
    border-radius: 50% !important;
    margin-right: 2px !important;
    width: 30px !important;
    height: 30px !important;
}
.member-perms .member-perm .name {
    margin-right: 8px !important;
}
```

_Thanks for making this theme available for everyone and free! Have a nice day._
